git:
  depth: 10
sudo: false
language: node_js
cache:
  yarn: true
  directories:
  - node_modules
node_js:
  - '8'
  - '6'
  - '4'

env:
  global:
    - PATH=$HOME/.yarn/bin:$PATH
    - JOB=test

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash

script:
  - 'if [ "$JOB" = "test" ]; then yarn test:ci; fi'
  - 'if [ "$JOB" = "lint" ]; then yarn lint; fi'

branches:
  except:
    - /^v\d+\.\d+\.\d+$/